### ISSUE TITLE
Running "npx create-fusion-app my-app" throws error without yarn

### ISSUE THREAD

**Issue by vivekamin** [fusionjs/create-fusion-app#27]
> npm version is 5.6.0, node version is 8.11.2.

Creating a new Fusion.js app in: /Users/vivek/vivek/fusion-framework-try/my-app

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by vivekamin** [comment]
@KevinGrandon which node version? I haven't tried with yarn. I am using Mac, installed node from official dmg

**Comment by KevinGrandon** [comment]
I'm on `8.11.3` and both yarn/npx work fine for me. I'll ask some folks to test the npx workflow, and maybe there's some additional logging we can add for more info? Not sure..

**Comment by vivekamin** [comment]
I will look into it.

**Comment by vivekamin** [comment]
When Yarn installed, npx works perfectly. When I uninstalled yarn, it stopped working. 
Using `brew install yarn --without-node` to install yarn.

**Comment by KevinGrandon** [comment]
Ah perfect - thank you for that information. I suppose this is due to: https://github.com/fusionjs/fusion-scaffolder/blob/master/index.js#L116

We are looking at rewriting this repo soon which will take care of this issue, or alternatively we can detect whether or not yarn is installed in fusion-scaffolder.

**Comment by jidemobell** [comment]
Issue has been fixed for me via slack support

**Comment by maihungdev** [comment]
same issue

**Comment by KevinGrandon** [comment]
Hi folks, sorry for the delay in responding here. So currently we require `yarn` to be installed on the host machine, and then `npx` will work. We do recommend using `yarn create` though. 

We have also recently fixed some windows errors, which should resolve some errors. If you continue to see errors on windows, please file a new ticket.
