### ISSUE TITLE
node 10 support

### ISSUE THREAD

**Issue by Evgenyx82** [fusionjs/create-fusion-app#28]
hi there, im getting error when run yarn create fusion-app, seems --ignore-engines works only with add or install yarn options

> $ yarn create fusion-app fusiontest --ignore-engines
> yarn create v1.9.2
> [1/4] 🔍  Resolving packages...
> warning Lockfile has incorrect entry for "aws-sdk@0.9.x". Ignoring it.
> Couldn't find any versions for "aws-sdk" that matches "0.9.x"
> ? Please choose a version of "aws-sdk" from this list: 2.286.2
> [2/4] 🚚  Fetching packages...
> [-----------------------------------------------------------------------] 0/835(node:35598) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

> $ node --version
> v10.8.0

how to fix the issue? )

**Comment by KevinGrandon** [comment]
Strange, I just tried on node 10.8 and it worked. I'm also not sure why you're getting `aws-sdk` warnings, we don't require that dependency.

Could you run this command and paste the output here? `yarn info create-fusion-app`

**Comment by brandoncc** [comment]
The root of this problem may lie in the `upath@1.0.4` package version. I saw this in the slack with someone else a couple of days ago and upath 1.0.5 removed the `<=9` constraint. `yarn upgrade upath` will likely fix it, since it should upgrade it to `1.1.0`.

**Comment by KevinGrandon** [comment]
Thanks for the useful information here. This will go out with our next release cycle.

**Comment by Evgenyx82** [comment]
i have been rolled back to 8.11, seems work fine...
same i have been upgrade upath

> $ yarn upgrade upath
> yarn upgrade v1.9.2
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> [4/4] 📃  Rebuilding all packages...
> success Saved lockfile.
> success Saved 0 new dependencies.
> ✨  Done in 0.09s.

then

> $ yarn create fusion-app fustiontest
> yarn create v1.9.2
> [1/4] 🔍  Resolving packages...
> warning Lockfile has incorrect entry for "aws-sdk@0.9.x". Ignoring it.
> Couldn't find any versions for "aws-sdk" that matches "0.9.x"
> ? Please choose a version of "aws-sdk" from this list: 2.289.0
> [2/4] 🚚  Fetching packages...
> warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/Users/username/Library/Caches/Yarn/v1/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic behavior, skipping.
> [----------------------------------------------------------------------] 0/1118(node:75012) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by Evgenyx82** [comment]
seems "yarn upgrade upath" not working as expected, it's still 1.0.4 insteed of 1.1.0 as suggested @brandoncc

**Comment by brandoncc** [comment]
Ah, sorry about that. @KevinGrandon merged a `yarn upgrade` which will handle this on the next deploy. I just realized that `yarn upgrade` would only affect existing projects, but you are creating a new one.

**Comment by KevinGrandon** [comment]
You should be able to run `yarn upgrade` locally, correct? I believe we're set to deploy later this week, and will talk to the team about getting some sort of schedule/documentation for this process.

**Comment by Evgenyx82** [comment]
@KevinGrandon Yes, i ran it locally. .Ok, i don't have any more questions. Thx for quick responses, keep this way ).
