### ISSUE TITLE
can i use typescript for the type checking.

### ISSUE THREAD

**Issue by zsirfs** [fusionjs/create-fusion-app#44]

**Comment by KevinGrandon** [comment]
Typescript is not supported as a first class citizen. It is possible however, here's some information on using typescript with Fusion.js. 

https://github.com/chrisgervang/fusion-cli
https://docs.google.com/document/d/1yBUyxk_kDcXrhC6S-WvjxcsgGIVpATEXQ60UcFIEQeY/edit

**Comment by zsirfs** [comment]
@KevinGrandon thanks.
